server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://babyorbit-api-1091443480665.us-east4.run.app/;
        proxy_set_header Host babyorbit-api-1091443480665.us-east4.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
    }
}
